CREATE OR ALTER procedure sig_mem (
    V_MEMB_ACTUAL FOLIO_TYPE)
returns (
    V_MEMB_SIG FOLIO_TYPE)
as
BEGIN
    SELECT
    CASE (SELECT si_no FROM dsa_es_numero(SUBSTRING(:V_MEMB_ACTUAL FROM 1 FOR 1)))
        WHEN 'S' THEN CAST(:V_MEMB_ACTUAL AS INTEGER) + 1
        ELSE CASE (SELECT si_no FROM dsa_es_numero(SUBSTRING(:V_MEMB_ACTUAL FROM 2 FOR 1)))
                WHEN 'S' THEN SUBSTRING(:V_MEMB_ACTUAL FROM 1 FOR 1) || (CAST(SUBSTRING(:V_MEMB_ACTUAL FROM 2 FOR 8) AS INTEGER) + 1)
                ELSE SUBSTRING(:V_MEMB_ACTUAL FROM 1 FOR 2) || (CAST(SUBSTRING(:V_MEMB_ACTUAL FROM 3 FOR 8) AS INTEGER) + 1)
             END
    END
    FROM rdb$database
    INTO :V_MEMB_SIG;
    SUSPEND;
END
